### ISSUE TITLE
Mark plants as dead

### ISSUE THREAD

**Issue by Rubenvdveen** [rutgerbrf/waterme#2]
Are you planning on creating a feature to mark a plant as dead? If nobody responds to the watering request, my plants will die and the bot will malfunction then.

**Comment by RichardLindhout** [comment]
+1

**Comment by rutgerbrf** [comment]
Currently, there is only the 'global' plants state, not a per-plant state. Different kinds of plants have different tolerations to drought, so currently this is not an option, nor is it currently a plan to support per-plant configurations.

**Comment by rutgerbrf** [comment]
-1

**Comment by RichardLindhout** [comment]
=0

**Comment by RichardLindhout** [comment]
I'm a mathematician which Can Create BlockChain Bitcoin Networks for your plant bot

**Comment by rutgerbrf** [comment]
Wow you must be a genius, please do
